/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using BookShop.ApiCaller.Client;
using BookShop.ApiCaller.Model;

namespace BookShop.ApiCaller.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        AuthorDTOApiResponse ApiAuthorDeleteIdDelete(int id, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        ApiResponse<AuthorDTOApiResponse> ApiAuthorDeleteIdDeleteWithHttpInfo(int id, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        AuthorDTOApiResponse ApiAuthorGetGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        ApiResponse<AuthorDTOApiResponse> ApiAuthorGetGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        AuthorDTOApiResponse ApiAuthorSetPost(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        ApiResponse<AuthorDTOApiResponse> ApiAuthorSetPostWithHttpInfo(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorDeleteIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuthorDTOApiResponse>> ApiAuthorDeleteIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorGetGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuthorDTOApiResponse>> ApiAuthorGetGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorSetPostAsync(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuthorDTOApiResponse>> ApiAuthorSetPostWithHttpInfoAsync(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorApi : IAuthorApiSync, IAuthorApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthorApi : IAuthorApi
    {
        private BookShop.ApiCaller.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthorApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthorApi(string basePath)
        {
            this.Configuration = BookShop.ApiCaller.Client.Configuration.MergeConfigurations(
                BookShop.ApiCaller.Client.GlobalConfiguration.Instance,
                new BookShop.ApiCaller.Client.Configuration { BasePath = basePath }
            );
            this.Client = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthorApi(BookShop.ApiCaller.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = BookShop.ApiCaller.Client.Configuration.MergeConfigurations(
                BookShop.ApiCaller.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AuthorApi(BookShop.ApiCaller.Client.ISynchronousClient client, BookShop.ApiCaller.Client.IAsynchronousClient asyncClient, BookShop.ApiCaller.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public BookShop.ApiCaller.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public BookShop.ApiCaller.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public BookShop.ApiCaller.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BookShop.ApiCaller.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        public AuthorDTOApiResponse ApiAuthorDeleteIdDelete(int id, int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = ApiAuthorDeleteIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> ApiAuthorDeleteIdDeleteWithHttpInfo(int id, int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", BookShop.ApiCaller.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorDeleteIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<AuthorDTOApiResponse>("/api/Author/Delete/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorDeleteIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorDeleteIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = await ApiAuthorDeleteIdDeleteWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse>> ApiAuthorDeleteIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", BookShop.ApiCaller.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorDeleteIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<AuthorDTOApiResponse>("/api/Author/Delete/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorDeleteIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        public AuthorDTOApiResponse ApiAuthorGetGet(int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = ApiAuthorGetGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> ApiAuthorGetGetWithHttpInfo(int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorGetGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AuthorDTOApiResponse>("/api/Author/Get", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorGetGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorGetGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = await ApiAuthorGetGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse>> ApiAuthorGetGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorGetGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AuthorDTOApiResponse>("/api/Author/Get", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorGetGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuthorDTOApiResponse</returns>
        public AuthorDTOApiResponse ApiAuthorSetPost(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = ApiAuthorSetPostWithHttpInfo(authorDTOApiRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuthorDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> ApiAuthorSetPostWithHttpInfo(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = authorDTOApiRequest;

            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorSetPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<AuthorDTOApiResponse>("/api/Author/Set", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorSetPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthorDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<AuthorDTOApiResponse> ApiAuthorSetPostAsync(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse> localVarResponse = await ApiAuthorSetPostWithHttpInfoAsync(authorDTOApiRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthorDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<AuthorDTOApiResponse>> ApiAuthorSetPostWithHttpInfoAsync(AuthorDTOApiRequest? authorDTOApiRequest = default(AuthorDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = authorDTOApiRequest;

            localVarRequestOptions.Operation = "AuthorApi.ApiAuthorSetPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AuthorDTOApiResponse>("/api/Author/Set", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthorSetPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
