/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using BookShop.ApiCaller.Client;
using BookShop.ApiCaller.Model;

namespace BookShop.ApiCaller.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRolePermissionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RolePermissionDTOApiResponse</returns>
        RolePermissionDTOApiResponse ApiRolePermissionDeleteIdDelete(int id, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RolePermissionDTOApiResponse</returns>
        ApiResponse<RolePermissionDTOApiResponse> ApiRolePermissionDeleteIdDeleteWithHttpInfo(int id, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RoleDTOApiResponse</returns>
        RoleDTOApiResponse ApiRolePermissionReportPost(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RoleDTOApiResponse</returns>
        ApiResponse<RoleDTOApiResponse> ApiRolePermissionReportPostWithHttpInfo(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RolePermissionDTOApiResponse</returns>
        RolePermissionDTOApiResponse ApiRolePermissionSetPost(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RolePermissionDTOApiResponse</returns>
        ApiResponse<RolePermissionDTOApiResponse> ApiRolePermissionSetPostWithHttpInfo(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRolePermissionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RolePermissionDTOApiResponse</returns>
        System.Threading.Tasks.Task<RolePermissionDTOApiResponse> ApiRolePermissionDeleteIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RolePermissionDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RolePermissionDTOApiResponse>> ApiRolePermissionDeleteIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleDTOApiResponse</returns>
        System.Threading.Tasks.Task<RoleDTOApiResponse> ApiRolePermissionReportPostAsync(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleDTOApiResponse>> ApiRolePermissionReportPostWithHttpInfoAsync(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RolePermissionDTOApiResponse</returns>
        System.Threading.Tasks.Task<RolePermissionDTOApiResponse> ApiRolePermissionSetPostAsync(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RolePermissionDTOApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RolePermissionDTOApiResponse>> ApiRolePermissionSetPostWithHttpInfoAsync(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRolePermissionApi : IRolePermissionApiSync, IRolePermissionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RolePermissionApi : IRolePermissionApi
    {
        private BookShop.ApiCaller.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RolePermissionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RolePermissionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RolePermissionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RolePermissionApi(string basePath)
        {
            this.Configuration = BookShop.ApiCaller.Client.Configuration.MergeConfigurations(
                BookShop.ApiCaller.Client.GlobalConfiguration.Instance,
                new BookShop.ApiCaller.Client.Configuration { BasePath = basePath }
            );
            this.Client = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RolePermissionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RolePermissionApi(BookShop.ApiCaller.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = BookShop.ApiCaller.Client.Configuration.MergeConfigurations(
                BookShop.ApiCaller.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BookShop.ApiCaller.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RolePermissionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RolePermissionApi(BookShop.ApiCaller.Client.ISynchronousClient client, BookShop.ApiCaller.Client.IAsynchronousClient asyncClient, BookShop.ApiCaller.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = BookShop.ApiCaller.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public BookShop.ApiCaller.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public BookShop.ApiCaller.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public BookShop.ApiCaller.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BookShop.ApiCaller.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RolePermissionDTOApiResponse</returns>
        public RolePermissionDTOApiResponse ApiRolePermissionDeleteIdDelete(int id, int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> localVarResponse = ApiRolePermissionDeleteIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RolePermissionDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> ApiRolePermissionDeleteIdDeleteWithHttpInfo(int id, int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", BookShop.ApiCaller.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionDeleteIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<RolePermissionDTOApiResponse>("/api/RolePermission/Delete/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionDeleteIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RolePermissionDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<RolePermissionDTOApiResponse> ApiRolePermissionDeleteIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> localVarResponse = await ApiRolePermissionDeleteIdDeleteWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RolePermissionDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse>> ApiRolePermissionDeleteIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", BookShop.ApiCaller.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionDeleteIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<RolePermissionDTOApiResponse>("/api/RolePermission/Delete/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionDeleteIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RoleDTOApiResponse</returns>
        public RoleDTOApiResponse ApiRolePermissionReportPost(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<RoleDTOApiResponse> localVarResponse = ApiRolePermissionReportPostWithHttpInfo(rolePermissionReportFilterDTOApiRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RoleDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<RoleDTOApiResponse> ApiRolePermissionReportPostWithHttpInfo(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = rolePermissionReportFilterDTOApiRequest;

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionReportPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RoleDTOApiResponse>("/api/RolePermission/Report", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionReportPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<RoleDTOApiResponse> ApiRolePermissionReportPostAsync(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<RoleDTOApiResponse> localVarResponse = await ApiRolePermissionReportPostWithHttpInfoAsync(rolePermissionReportFilterDTOApiRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionReportFilterDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<RoleDTOApiResponse>> ApiRolePermissionReportPostWithHttpInfoAsync(RolePermissionReportFilterDTOApiRequest? rolePermissionReportFilterDTOApiRequest = default(RolePermissionReportFilterDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = rolePermissionReportFilterDTOApiRequest;

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionReportPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<RoleDTOApiResponse>("/api/RolePermission/Report", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionReportPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RolePermissionDTOApiResponse</returns>
        public RolePermissionDTOApiResponse ApiRolePermissionSetPost(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> localVarResponse = ApiRolePermissionSetPostWithHttpInfo(rolePermissionDTOApiRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RolePermissionDTOApiResponse</returns>
        public BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> ApiRolePermissionSetPostWithHttpInfo(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0)
        {
            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = rolePermissionDTOApiRequest;

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionSetPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RolePermissionDTOApiResponse>("/api/RolePermission/Set", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionSetPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RolePermissionDTOApiResponse</returns>
        public async System.Threading.Tasks.Task<RolePermissionDTOApiResponse> ApiRolePermissionSetPostAsync(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse> localVarResponse = await ApiRolePermissionSetPostWithHttpInfoAsync(rolePermissionDTOApiRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="BookShop.ApiCaller.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolePermissionDTOApiRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RolePermissionDTOApiResponse)</returns>
        public async System.Threading.Tasks.Task<BookShop.ApiCaller.Client.ApiResponse<RolePermissionDTOApiResponse>> ApiRolePermissionSetPostWithHttpInfoAsync(RolePermissionDTOApiRequest? rolePermissionDTOApiRequest = default(RolePermissionDTOApiRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            BookShop.ApiCaller.Client.RequestOptions localVarRequestOptions = new BookShop.ApiCaller.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BookShop.ApiCaller.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = rolePermissionDTOApiRequest;

            localVarRequestOptions.Operation = "RolePermissionApi.ApiRolePermissionSetPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("WebToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("WebToken", this.Configuration.GetApiKeyWithPrefix("WebToken"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<RolePermissionDTOApiResponse>("/api/RolePermission/Set", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolePermissionSetPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
