/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// BookDTO
    /// </summary>
    [DataContract(Name = "BookDTO")]
    public partial class BookDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BookDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="title">title.</param>
        /// <param name="isbn">isbn.</param>
        /// <param name="publisherID">publisherID.</param>
        /// <param name="publisherTitle">publisherTitle.</param>
        /// <param name="groupsIds">groupsIds.</param>
        /// <param name="authorIds">authorIds.</param>
        /// <param name="translatorIds">translatorIds.</param>
        /// <param name="createDate">createDate.</param>
        /// <param name="price">price.</param>
        /// <param name="pageNumbers">pageNumbers.</param>
        /// <param name="imageKey">imageKey.</param>
        public BookDTO(int id = default(int), string message = default(string), string title = default(string), string isbn = default(string), int publisherID = default(int), string publisherTitle = default(string), List<int> groupsIds = default(List<int>), List<int> authorIds = default(List<int>), List<int> translatorIds = default(List<int>), DateTime createDate = default(DateTime), double price = default(double), int pageNumbers = default(int), string imageKey = default(string))
        {
            this.Id = id;
            this.Message = message;
            this.Title = title;
            this.Isbn = isbn;
            this.PublisherID = publisherID;
            this.PublisherTitle = publisherTitle;
            this.GroupsIds = groupsIds;
            this.AuthorIds = authorIds;
            this.TranslatorIds = translatorIds;
            this.CreateDate = createDate;
            this.Price = price;
            this.PageNumbers = pageNumbers;
            this.ImageKey = imageKey;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Isbn
        /// </summary>
        [DataMember(Name = "isbn", EmitDefaultValue = true)]
        public string Isbn { get; set; }

        /// <summary>
        /// Gets or Sets PublisherID
        /// </summary>
        [DataMember(Name = "publisherID", EmitDefaultValue = false)]
        public int PublisherID { get; set; }

        /// <summary>
        /// Gets or Sets PublisherTitle
        /// </summary>
        [DataMember(Name = "publisherTitle", EmitDefaultValue = true)]
        public string PublisherTitle { get; set; }

        /// <summary>
        /// Gets or Sets GroupsIds
        /// </summary>
        [DataMember(Name = "groupsIds", EmitDefaultValue = true)]
        public List<int> GroupsIds { get; set; }

        /// <summary>
        /// Gets or Sets AuthorIds
        /// </summary>
        [DataMember(Name = "authorIds", EmitDefaultValue = true)]
        public List<int> AuthorIds { get; set; }

        /// <summary>
        /// Gets or Sets TranslatorIds
        /// </summary>
        [DataMember(Name = "translatorIds", EmitDefaultValue = true)]
        public List<int> TranslatorIds { get; set; }

        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [DataMember(Name = "createDate", EmitDefaultValue = false)]
        public DateTime CreateDate { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public double Price { get; set; }

        /// <summary>
        /// Gets or Sets PageNumbers
        /// </summary>
        [DataMember(Name = "pageNumbers", EmitDefaultValue = false)]
        public int PageNumbers { get; set; }

        /// <summary>
        /// Gets or Sets ImageKey
        /// </summary>
        [DataMember(Name = "imageKey", EmitDefaultValue = true)]
        public string ImageKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BookDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Isbn: ").Append(Isbn).Append("\n");
            sb.Append("  PublisherID: ").Append(PublisherID).Append("\n");
            sb.Append("  PublisherTitle: ").Append(PublisherTitle).Append("\n");
            sb.Append("  GroupsIds: ").Append(GroupsIds).Append("\n");
            sb.Append("  AuthorIds: ").Append(AuthorIds).Append("\n");
            sb.Append("  TranslatorIds: ").Append(TranslatorIds).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PageNumbers: ").Append(PageNumbers).Append("\n");
            sb.Append("  ImageKey: ").Append(ImageKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
