/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// BookReportFilterDTO
    /// </summary>
    [DataContract(Name = "BookReportFilterDTO")]
    public partial class BookReportFilterDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BookReportFilterDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="bookIDs">bookIDs.</param>
        /// <param name="groupIDs">groupIDs.</param>
        /// <param name="publisherIDs">publisherIDs.</param>
        /// <param name="authorIDs">authorIDs.</param>
        /// <param name="fromPrice">fromPrice.</param>
        /// <param name="toPrice">toPrice.</param>
        /// <param name="bookTitle">bookTitle.</param>
        public BookReportFilterDTO(int id = default(int), string message = default(string), List<int> bookIDs = default(List<int>), List<int> groupIDs = default(List<int>), List<int> publisherIDs = default(List<int>), List<int> authorIDs = default(List<int>), double? fromPrice = default(double?), double? toPrice = default(double?), string bookTitle = default(string))
        {
            this.Id = id;
            this.Message = message;
            this.BookIDs = bookIDs;
            this.GroupIDs = groupIDs;
            this.PublisherIDs = publisherIDs;
            this.AuthorIDs = authorIDs;
            this.FromPrice = fromPrice;
            this.ToPrice = toPrice;
            this.BookTitle = bookTitle;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets BookIDs
        /// </summary>
        [DataMember(Name = "bookIDs", EmitDefaultValue = true)]
        public List<int> BookIDs { get; set; }

        /// <summary>
        /// Gets or Sets GroupIDs
        /// </summary>
        [DataMember(Name = "groupIDs", EmitDefaultValue = true)]
        public List<int> GroupIDs { get; set; }

        /// <summary>
        /// Gets or Sets PublisherIDs
        /// </summary>
        [DataMember(Name = "publisherIDs", EmitDefaultValue = true)]
        public List<int> PublisherIDs { get; set; }

        /// <summary>
        /// Gets or Sets AuthorIDs
        /// </summary>
        [DataMember(Name = "authorIDs", EmitDefaultValue = true)]
        public List<int> AuthorIDs { get; set; }

        /// <summary>
        /// Gets or Sets FromPrice
        /// </summary>
        [DataMember(Name = "fromPrice", EmitDefaultValue = true)]
        public double? FromPrice { get; set; }

        /// <summary>
        /// Gets or Sets ToPrice
        /// </summary>
        [DataMember(Name = "toPrice", EmitDefaultValue = true)]
        public double? ToPrice { get; set; }

        /// <summary>
        /// Gets or Sets BookTitle
        /// </summary>
        [DataMember(Name = "bookTitle", EmitDefaultValue = true)]
        public string BookTitle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BookReportFilterDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  BookIDs: ").Append(BookIDs).Append("\n");
            sb.Append("  GroupIDs: ").Append(GroupIDs).Append("\n");
            sb.Append("  PublisherIDs: ").Append(PublisherIDs).Append("\n");
            sb.Append("  AuthorIDs: ").Append(AuthorIDs).Append("\n");
            sb.Append("  FromPrice: ").Append(FromPrice).Append("\n");
            sb.Append("  ToPrice: ").Append(ToPrice).Append("\n");
            sb.Append("  BookTitle: ").Append(BookTitle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
