/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// CreateOrderDTO
    /// </summary>
    [DataContract(Name = "CreateOrderDTO")]
    public partial class CreateOrderDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrderDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="customerId">customerId.</param>
        /// <param name="isInstallment">isInstallment.</param>
        /// <param name="installmentCount">installmentCount.</param>
        /// <param name="description">description.</param>
        /// <param name="orderBooks">orderBooks.</param>
        /// <param name="customerAddressId">customerAddressId.</param>
        public CreateOrderDTO(int id = default(int), string message = default(string), int customerId = default(int), bool isInstallment = default(bool), int installmentCount = default(int), string description = default(string), List<OrderBookDTO> orderBooks = default(List<OrderBookDTO>), int customerAddressId = default(int))
        {
            this.Id = id;
            this.Message = message;
            this.CustomerId = customerId;
            this.IsInstallment = isInstallment;
            this.InstallmentCount = installmentCount;
            this.Description = description;
            this.OrderBooks = orderBooks;
            this.CustomerAddressId = customerAddressId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets IsInstallment
        /// </summary>
        [DataMember(Name = "isInstallment", EmitDefaultValue = true)]
        public bool IsInstallment { get; set; }

        /// <summary>
        /// Gets or Sets InstallmentCount
        /// </summary>
        [DataMember(Name = "installmentCount", EmitDefaultValue = false)]
        public int InstallmentCount { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets OrderBooks
        /// </summary>
        [DataMember(Name = "orderBooks", EmitDefaultValue = true)]
        public List<OrderBookDTO> OrderBooks { get; set; }

        /// <summary>
        /// Gets or Sets CustomerAddressId
        /// </summary>
        [DataMember(Name = "customerAddressId", EmitDefaultValue = false)]
        public int CustomerAddressId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrderDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  IsInstallment: ").Append(IsInstallment).Append("\n");
            sb.Append("  InstallmentCount: ").Append(InstallmentCount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OrderBooks: ").Append(OrderBooks).Append("\n");
            sb.Append("  CustomerAddressId: ").Append(CustomerAddressId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
