/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// CustomerAddressDTO
    /// </summary>
    [DataContract(Name = "CustomerAddressDTO")]
    public partial class CustomerAddressDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerAddressDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="customerId">customerId.</param>
        /// <param name="province">province.</param>
        /// <param name="city">city.</param>
        /// <param name="street">street.</param>
        /// <param name="alley">alley.</param>
        /// <param name="unit">unit.</param>
        /// <param name="postalCode">postalCode.</param>
        /// <param name="plaque">plaque.</param>
        public CustomerAddressDTO(int id = default(int), string message = default(string), int customerId = default(int), string province = default(string), string city = default(string), string street = default(string), string alley = default(string), string unit = default(string), string postalCode = default(string), string plaque = default(string))
        {
            this.Id = id;
            this.Message = message;
            this.CustomerId = customerId;
            this.Province = province;
            this.City = city;
            this.Street = street;
            this.Alley = alley;
            this.Unit = unit;
            this.PostalCode = postalCode;
            this.Plaque = plaque;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets Province
        /// </summary>
        [DataMember(Name = "province", EmitDefaultValue = true)]
        public string Province { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name = "city", EmitDefaultValue = true)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets Street
        /// </summary>
        [DataMember(Name = "street", EmitDefaultValue = true)]
        public string Street { get; set; }

        /// <summary>
        /// Gets or Sets Alley
        /// </summary>
        [DataMember(Name = "alley", EmitDefaultValue = true)]
        public string Alley { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", EmitDefaultValue = true)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        [DataMember(Name = "postalCode", EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or Sets Plaque
        /// </summary>
        [DataMember(Name = "plaque", EmitDefaultValue = true)]
        public string Plaque { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerAddressDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Province: ").Append(Province).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Street: ").Append(Street).Append("\n");
            sb.Append("  Alley: ").Append(Alley).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Plaque: ").Append(Plaque).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
