/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// InstallmentDetailDTO
    /// </summary>
    [DataContract(Name = "InstallmentDetailDTO")]
    public partial class InstallmentDetailDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentDetailDTO" /> class.
        /// </summary>
        /// <param name="firstInstallmentDate">firstInstallmentDate.</param>
        /// <param name="installmentPaymentStatus">installmentPaymentStatus.</param>
        public InstallmentDetailDTO(DateTime firstInstallmentDate = default(DateTime), string installmentPaymentStatus = default(string))
        {
            this.FirstInstallmentDate = firstInstallmentDate;
            this.InstallmentPaymentStatus = installmentPaymentStatus;
        }

        /// <summary>
        /// Gets or Sets FirstInstallmentDate
        /// </summary>
        [DataMember(Name = "firstInstallmentDate", EmitDefaultValue = false)]
        public DateTime FirstInstallmentDate { get; set; }

        /// <summary>
        /// Gets or Sets InstallmentPaymentStatus
        /// </summary>
        [DataMember(Name = "installmentPaymentStatus", EmitDefaultValue = true)]
        public string InstallmentPaymentStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallmentDetailDTO {\n");
            sb.Append("  FirstInstallmentDate: ").Append(FirstInstallmentDate).Append("\n");
            sb.Append("  InstallmentPaymentStatus: ").Append(InstallmentPaymentStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
