/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// LoginResponseDTO
    /// </summary>
    [DataContract(Name = "LoginResponseDTO")]
    public partial class LoginResponseDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginResponseDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="userId">userId.</param>
        /// <param name="sessionIdentifier">sessionIdentifier.</param>
        /// <param name="webToken">webToken.</param>
        public LoginResponseDTO(int id = default(int), string message = default(string), int userId = default(int), string sessionIdentifier = default(string), string webToken = default(string))
        {
            this.Id = id;
            this.Message = message;
            this.UserId = userId;
            this.SessionIdentifier = sessionIdentifier;
            this.WebToken = webToken;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets SessionIdentifier
        /// </summary>
        [DataMember(Name = "sessionIdentifier", EmitDefaultValue = true)]
        public string SessionIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets WebToken
        /// </summary>
        [DataMember(Name = "webToken", EmitDefaultValue = true)]
        public string WebToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginResponseDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  SessionIdentifier: ").Append(SessionIdentifier).Append("\n");
            sb.Append("  WebToken: ").Append(WebToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
