/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// LoginResponseDTOApiResponse
    /// </summary>
    [DataContract(Name = "LoginResponseDTOApiResponse")]
    public partial class LoginResponseDTOApiResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginResponseDTOApiResponse" /> class.
        /// </summary>
        /// <param name="message">message.</param>
        /// <param name="isSuccess">isSuccess.</param>
        /// <param name="responseDTO">responseDTO.</param>
        /// <param name="responseDTOList">responseDTOList.</param>
        public LoginResponseDTOApiResponse(string message = default(string), bool isSuccess = default(bool), LoginResponseDTO responseDTO = default(LoginResponseDTO), List<LoginResponseDTO> responseDTOList = default(List<LoginResponseDTO>))
        {
            this.Message = message;
            this.IsSuccess = isSuccess;
            this.ResponseDTO = responseDTO;
            this.ResponseDTOList = responseDTOList;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets IsSuccess
        /// </summary>
        [DataMember(Name = "isSuccess", EmitDefaultValue = true)]
        public bool IsSuccess { get; set; }

        /// <summary>
        /// Gets or Sets ResponseDTO
        /// </summary>
        [DataMember(Name = "responseDTO", EmitDefaultValue = false)]
        public LoginResponseDTO ResponseDTO { get; set; }

        /// <summary>
        /// Gets or Sets ResponseDTOList
        /// </summary>
        [DataMember(Name = "responseDTOList", EmitDefaultValue = true)]
        public List<LoginResponseDTO> ResponseDTOList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginResponseDTOApiResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  ResponseDTO: ").Append(ResponseDTO).Append("\n");
            sb.Append("  ResponseDTOList: ").Append(ResponseDTOList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
