/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// OrderReportFilterDTO
    /// </summary>
    [DataContract(Name = "OrderReportFilterDTO")]
    public partial class OrderReportFilterDTO : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public OrderStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderReportFilterDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="customerIDs">customerIDs.</param>
        /// <param name="userIDs">userIDs.</param>
        /// <param name="isInstallment">isInstallment.</param>
        /// <param name="status">status.</param>
        /// <param name="fromCreateDate">fromCreateDate.</param>
        /// <param name="toCreateDate">toCreateDate.</param>
        public OrderReportFilterDTO(int id = default(int), string message = default(string), List<int> customerIDs = default(List<int>), List<int> userIDs = default(List<int>), bool? isInstallment = default(bool?), OrderStatus? status = default(OrderStatus?), DateTime fromCreateDate = default(DateTime), DateTime toCreateDate = default(DateTime))
        {
            this.Id = id;
            this.Message = message;
            this.CustomerIDs = customerIDs;
            this.UserIDs = userIDs;
            this.IsInstallment = isInstallment;
            this.Status = status;
            this.FromCreateDate = fromCreateDate;
            this.ToCreateDate = toCreateDate;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets CustomerIDs
        /// </summary>
        [DataMember(Name = "customerIDs", EmitDefaultValue = true)]
        public List<int> CustomerIDs { get; set; }

        /// <summary>
        /// Gets or Sets UserIDs
        /// </summary>
        [DataMember(Name = "userIDs", EmitDefaultValue = true)]
        public List<int> UserIDs { get; set; }

        /// <summary>
        /// Gets or Sets IsInstallment
        /// </summary>
        [DataMember(Name = "isInstallment", EmitDefaultValue = true)]
        public bool? IsInstallment { get; set; }

        /// <summary>
        /// Gets or Sets FromCreateDate
        /// </summary>
        [DataMember(Name = "fromCreateDate", EmitDefaultValue = false)]
        public DateTime FromCreateDate { get; set; }

        /// <summary>
        /// Gets or Sets ToCreateDate
        /// </summary>
        [DataMember(Name = "toCreateDate", EmitDefaultValue = false)]
        public DateTime ToCreateDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderReportFilterDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  CustomerIDs: ").Append(CustomerIDs).Append("\n");
            sb.Append("  UserIDs: ").Append(UserIDs).Append("\n");
            sb.Append("  IsInstallment: ").Append(IsInstallment).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  FromCreateDate: ").Append(FromCreateDate).Append("\n");
            sb.Append("  ToCreateDate: ").Append(ToCreateDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
