/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// OrderDTO
    /// </summary>
    [DataContract(Name = "OrderDTO")]
    public partial class OrderDTO : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public OrderStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="customerId">customerId.</param>
        /// <param name="customerFullName">customerFullName.</param>
        /// <param name="createDate">createDate.</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="status">status.</param>
        /// <param name="statusDescription">statusDescription.</param>
        /// <param name="installmentDetail">installmentDetail.</param>
        /// <param name="installmentDetailDTO">installmentDetailDTO.</param>
        /// <param name="installmentList">installmentList.</param>
        /// <param name="isInstallment">isInstallment.</param>
        /// <param name="installmentCount">installmentCount.</param>
        /// <param name="description">description.</param>
        /// <param name="orderBooks">orderBooks.</param>
        /// <param name="totalAmount">totalAmount.</param>
        /// <param name="customerAddressId">customerAddressId.</param>
        public OrderDTO(int id = default(int), string message = default(string), int customerId = default(int), string customerFullName = default(string), DateTime createDate = default(DateTime), DateTime? endDate = default(DateTime?), OrderStatus? status = default(OrderStatus?), string statusDescription = default(string), string installmentDetail = default(string), InstallmentDetailDTO installmentDetailDTO = default(InstallmentDetailDTO), List<InstallmentDTO> installmentList = default(List<InstallmentDTO>), bool isInstallment = default(bool), int installmentCount = default(int), string description = default(string), List<OrderBookDTO> orderBooks = default(List<OrderBookDTO>), double totalAmount = default(double), int customerAddressId = default(int))
        {
            this.Id = id;
            this.Message = message;
            this.CustomerId = customerId;
            this.CustomerFullName = customerFullName;
            this.CreateDate = createDate;
            this.EndDate = endDate;
            this.Status = status;
            this.StatusDescription = statusDescription;
            this.InstallmentDetail = installmentDetail;
            this.InstallmentDetailDTO = installmentDetailDTO;
            this.InstallmentList = installmentList;
            this.IsInstallment = isInstallment;
            this.InstallmentCount = installmentCount;
            this.Description = description;
            this.OrderBooks = orderBooks;
            this.TotalAmount = totalAmount;
            this.CustomerAddressId = customerAddressId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerFullName
        /// </summary>
        [DataMember(Name = "customerFullName", EmitDefaultValue = true)]
        public string CustomerFullName { get; set; }

        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [DataMember(Name = "createDate", EmitDefaultValue = false)]
        public DateTime CreateDate { get; set; }

        /// <summary>
        /// Gets or Sets EndDate
        /// </summary>
        [DataMember(Name = "endDate", EmitDefaultValue = true)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Gets or Sets StatusDescription
        /// </summary>
        [DataMember(Name = "statusDescription", EmitDefaultValue = true)]
        public string StatusDescription { get; set; }

        /// <summary>
        /// Gets or Sets StatusStr
        /// </summary>
        [DataMember(Name = "statusStr", EmitDefaultValue = true)]
        public string StatusStr { get; private set; }

        /// <summary>
        /// Returns false as StatusStr should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatusStr()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets InstallmentDetail
        /// </summary>
        [DataMember(Name = "installmentDetail", EmitDefaultValue = true)]
        public string InstallmentDetail { get; set; }

        /// <summary>
        /// Gets or Sets InstallmentDetailDTO
        /// </summary>
        [DataMember(Name = "installmentDetailDTO", EmitDefaultValue = false)]
        public InstallmentDetailDTO InstallmentDetailDTO { get; set; }

        /// <summary>
        /// Gets or Sets InstallmentList
        /// </summary>
        [DataMember(Name = "installmentList", EmitDefaultValue = true)]
        public List<InstallmentDTO> InstallmentList { get; set; }

        /// <summary>
        /// Gets or Sets IsInstallment
        /// </summary>
        [DataMember(Name = "isInstallment", EmitDefaultValue = true)]
        public bool IsInstallment { get; set; }

        /// <summary>
        /// Gets or Sets InstallmentCount
        /// </summary>
        [DataMember(Name = "installmentCount", EmitDefaultValue = false)]
        public int InstallmentCount { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets OrderBooks
        /// </summary>
        [DataMember(Name = "orderBooks", EmitDefaultValue = true)]
        public List<OrderBookDTO> OrderBooks { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [DataMember(Name = "totalAmount", EmitDefaultValue = false)]
        public double TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets CustomerAddressId
        /// </summary>
        [DataMember(Name = "customerAddressId", EmitDefaultValue = false)]
        public int CustomerAddressId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  CustomerFullName: ").Append(CustomerFullName).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusDescription: ").Append(StatusDescription).Append("\n");
            sb.Append("  StatusStr: ").Append(StatusStr).Append("\n");
            sb.Append("  InstallmentDetail: ").Append(InstallmentDetail).Append("\n");
            sb.Append("  InstallmentDetailDTO: ").Append(InstallmentDetailDTO).Append("\n");
            sb.Append("  InstallmentList: ").Append(InstallmentList).Append("\n");
            sb.Append("  IsInstallment: ").Append(IsInstallment).Append("\n");
            sb.Append("  InstallmentCount: ").Append(InstallmentCount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OrderBooks: ").Append(OrderBooks).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  CustomerAddressId: ").Append(CustomerAddressId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
