/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// Enum values: NotSubmitted &#x3D; 0, AwaitingAccept &#x3D; 1, Rejected &#x3D; 2, Accepted &#x3D; 3
    /// </summary>
    /// <value>Enum values: NotSubmitted &#x3D; 0, AwaitingAccept &#x3D; 1, Rejected &#x3D; 2, Accepted &#x3D; 3</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderGuaranteeStatus
    {
        /// <summary>
        /// Enum NotSubmitted for value: NotSubmitted
        /// </summary>
        [EnumMember(Value = "NotSubmitted")]
        NotSubmitted = 1,

        /// <summary>
        /// Enum AwaitingAccept for value: AwaitingAccept
        /// </summary>
        [EnumMember(Value = "AwaitingAccept")]
        AwaitingAccept = 2,

        /// <summary>
        /// Enum Rejected for value: Rejected
        /// </summary>
        [EnumMember(Value = "Rejected")]
        Rejected = 3,

        /// <summary>
        /// Enum Accepted for value: Accepted
        /// </summary>
        [EnumMember(Value = "Accepted")]
        Accepted = 4
    }

}
