/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// Enum values: Post &#x3D; 0, Image &#x3D; 1, Both &#x3D; 2
    /// </summary>
    /// <value>Enum values: Post &#x3D; 0, Image &#x3D; 1, Both &#x3D; 2</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderGuaranteeReceiptMethod
    {
        /// <summary>
        /// Enum Post for value: Post
        /// </summary>
        [EnumMember(Value = "Post")]
        Post = 1,

        /// <summary>
        /// Enum Image for value: Image
        /// </summary>
        [EnumMember(Value = "Image")]
        Image = 2,

        /// <summary>
        /// Enum Both for value: Both
        /// </summary>
        [EnumMember(Value = "Both")]
        Both = 3
    }

}
