/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// OrderGuaranteeDTO
    /// </summary>
    [DataContract(Name = "OrderGuaranteeDTO")]
    public partial class OrderGuaranteeDTO : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public OrderGuaranteeStatus? Status { get; set; }

        /// <summary>
        /// Gets or Sets ReceiptMethod
        /// </summary>
        [DataMember(Name = "receiptMethod", EmitDefaultValue = false)]
        public OrderGuaranteeReceiptMethod? ReceiptMethod { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderGuaranteeDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="orderId">orderId.</param>
        /// <param name="guaranteeId">guaranteeId.</param>
        /// <param name="status">status.</param>
        /// <param name="statusDescription">statusDescription.</param>
        /// <param name="imageKey">imageKey.</param>
        /// <param name="receiptMethod">receiptMethod.</param>
        public OrderGuaranteeDTO(int id = default(int), string message = default(string), int orderId = default(int), int guaranteeId = default(int), OrderGuaranteeStatus? status = default(OrderGuaranteeStatus?), string statusDescription = default(string), string imageKey = default(string), OrderGuaranteeReceiptMethod? receiptMethod = default(OrderGuaranteeReceiptMethod?))
        {
            this.Id = id;
            this.Message = message;
            this.OrderId = orderId;
            this.GuaranteeId = guaranteeId;
            this.Status = status;
            this.StatusDescription = statusDescription;
            this.ImageKey = imageKey;
            this.ReceiptMethod = receiptMethod;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "orderId", EmitDefaultValue = false)]
        public int OrderId { get; set; }

        /// <summary>
        /// Gets or Sets GuaranteeId
        /// </summary>
        [DataMember(Name = "guaranteeId", EmitDefaultValue = false)]
        public int GuaranteeId { get; set; }

        /// <summary>
        /// Gets or Sets StatusStr
        /// </summary>
        [DataMember(Name = "statusStr", EmitDefaultValue = true)]
        public string StatusStr { get; private set; }

        /// <summary>
        /// Returns false as StatusStr should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatusStr()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets StatusDescription
        /// </summary>
        [DataMember(Name = "statusDescription", EmitDefaultValue = true)]
        public string StatusDescription { get; set; }

        /// <summary>
        /// Gets or Sets ImageKey
        /// </summary>
        [DataMember(Name = "imageKey", EmitDefaultValue = true)]
        public string ImageKey { get; set; }

        /// <summary>
        /// Gets or Sets ReceiptMethodStr
        /// </summary>
        [DataMember(Name = "receiptMethodStr", EmitDefaultValue = true)]
        public string ReceiptMethodStr { get; private set; }

        /// <summary>
        /// Returns false as ReceiptMethodStr should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeReceiptMethodStr()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderGuaranteeDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  GuaranteeId: ").Append(GuaranteeId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusStr: ").Append(StatusStr).Append("\n");
            sb.Append("  StatusDescription: ").Append(StatusDescription).Append("\n");
            sb.Append("  ImageKey: ").Append(ImageKey).Append("\n");
            sb.Append("  ReceiptMethod: ").Append(ReceiptMethod).Append("\n");
            sb.Append("  ReceiptMethodStr: ").Append(ReceiptMethodStr).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
