/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// Enum values: AwaitingConfirmation &#x3D; 0, Accepted &#x3D; 1, AwaitingPayment &#x3D; 2, GetGuarantee &#x3D; 3, ValidateGuarantee &#x3D; 4, Preparing &#x3D; 5, Sent &#x3D; 6
    /// </summary>
    /// <value>Enum values: AwaitingConfirmation &#x3D; 0, Accepted &#x3D; 1, AwaitingPayment &#x3D; 2, GetGuarantee &#x3D; 3, ValidateGuarantee &#x3D; 4, Preparing &#x3D; 5, Sent &#x3D; 6</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderStatus
    {
        /// <summary>
        /// Enum AwaitingConfirmation for value: AwaitingConfirmation
        /// </summary>
        [EnumMember(Value = "AwaitingConfirmation")]
        AwaitingConfirmation = 1,

        /// <summary>
        /// Enum Accepted for value: Accepted
        /// </summary>
        [EnumMember(Value = "Accepted")]
        Accepted = 2,

        /// <summary>
        /// Enum AwaitingPayment for value: AwaitingPayment
        /// </summary>
        [EnumMember(Value = "AwaitingPayment")]
        AwaitingPayment = 3,

        /// <summary>
        /// Enum GetGuarantee for value: GetGuarantee
        /// </summary>
        [EnumMember(Value = "GetGuarantee")]
        GetGuarantee = 4,

        /// <summary>
        /// Enum ValidateGuarantee for value: ValidateGuarantee
        /// </summary>
        [EnumMember(Value = "ValidateGuarantee")]
        ValidateGuarantee = 5,

        /// <summary>
        /// Enum Preparing for value: Preparing
        /// </summary>
        [EnumMember(Value = "Preparing")]
        Preparing = 6,

        /// <summary>
        /// Enum Sent for value: Sent
        /// </summary>
        [EnumMember(Value = "Sent")]
        Sent = 7
    }

}
