/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// UserRoleDTOApiRequest
    /// </summary>
    [DataContract(Name = "UserRoleDTOApiRequest")]
    public partial class UserRoleDTOApiRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRoleDTOApiRequest" /> class.
        /// </summary>
        /// <param name="iDs">iDs.</param>
        /// <param name="id">id.</param>
        /// <param name="pageNumber">pageNumber.</param>
        /// <param name="count">count.</param>
        /// <param name="requestDTO">requestDTO.</param>
        /// <param name="requestDTOList">requestDTOList.</param>
        public UserRoleDTOApiRequest(List<int> iDs = default(List<int>), int? id = default(int?), int pageNumber = default(int), int count = default(int), UserRoleDTO requestDTO = default(UserRoleDTO), List<UserRoleDTO> requestDTOList = default(List<UserRoleDTO>))
        {
            this.IDs = iDs;
            this.Id = id;
            this.PageNumber = pageNumber;
            this.Count = count;
            this.RequestDTO = requestDTO;
            this.RequestDTOList = requestDTOList;
        }

        /// <summary>
        /// Gets or Sets IDs
        /// </summary>
        [DataMember(Name = "iDs", EmitDefaultValue = true)]
        public List<int> IDs { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets PageNumber
        /// </summary>
        [DataMember(Name = "pageNumber", EmitDefaultValue = false)]
        public int PageNumber { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets RequestDTO
        /// </summary>
        [DataMember(Name = "requestDTO", EmitDefaultValue = false)]
        public UserRoleDTO RequestDTO { get; set; }

        /// <summary>
        /// Gets or Sets RequestDTOList
        /// </summary>
        [DataMember(Name = "requestDTOList", EmitDefaultValue = true)]
        public List<UserRoleDTO> RequestDTOList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRoleDTOApiRequest {\n");
            sb.Append("  IDs: ").Append(IDs).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  RequestDTO: ").Append(RequestDTO).Append("\n");
            sb.Append("  RequestDTOList: ").Append(RequestDTOList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
