/*
 * Book shop Api
 *
 * This is Book shop Api
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BookShop.ApiCaller.Client.OpenAPIDateConverter;

namespace BookShop.ApiCaller.Model
{
    /// <summary>
    /// UserReportFilterDTO
    /// </summary>
    [DataContract(Name = "UserReportFilterDTO")]
    public partial class UserReportFilterDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserReportFilterDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="message">message.</param>
        /// <param name="userName">userName.</param>
        /// <param name="userIDs">userIDs.</param>
        /// <param name="permissionKey">permissionKey.</param>
        /// <param name="loadUserRoles">loadUserRoles.</param>
        public UserReportFilterDTO(int id = default(int), string message = default(string), string userName = default(string), List<int> userIDs = default(List<int>), string permissionKey = default(string), bool loadUserRoles = default(bool))
        {
            this.Id = id;
            this.Message = message;
            this.UserName = userName;
            this.UserIDs = userIDs;
            this.PermissionKey = permissionKey;
            this.LoadUserRoles = loadUserRoles;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [DataMember(Name = "userName", EmitDefaultValue = true)]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or Sets UserIDs
        /// </summary>
        [DataMember(Name = "userIDs", EmitDefaultValue = true)]
        public List<int> UserIDs { get; set; }

        /// <summary>
        /// Gets or Sets PermissionKey
        /// </summary>
        [DataMember(Name = "permissionKey", EmitDefaultValue = true)]
        public string PermissionKey { get; set; }

        /// <summary>
        /// Gets or Sets LoadUserRoles
        /// </summary>
        [DataMember(Name = "loadUserRoles", EmitDefaultValue = true)]
        public bool LoadUserRoles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserReportFilterDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  UserIDs: ").Append(UserIDs).Append("\n");
            sb.Append("  PermissionKey: ").Append(PermissionKey).Append("\n");
            sb.Append("  LoadUserRoles: ").Append(LoadUserRoles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
